### ISSUE TITLE
更新依頼と提案

### ISSUE THREAD

**Issue by hinataaki** [KashEight/JP-Localize#2]
お久しぶりです。

- 日本語訳のファイルの更新のお願い
(JP-Localize/lua/lang/japanese.lua)の更新日が1年半ほど前なので最新版に差し替えをお願いしたいです。

それと、Pager字幕は実装不可だったということであれば
(JP-Localize/lua/lang/english.lua)もダウンロードできるファイルから削除してもいいのではないでしょうか？
翻訳されていても字幕として表示されない部分もゲーム内に結構あるようですからね。

**Comment by KashEight** [comment]
お久しぶりです.

## 日本語訳ファイルについて
確かに最後のコミットが去年の 4/18 なのでけっこう古いものですね… 
今日の夜あたりに最新版のものに差し替えておきます.
本当はスプレッドシートから自動的に最新の情報手に入れてアップデートしたいですけどけっこう面倒なんですよね…

## Pager 字幕について
今までは字幕を面倒な方法でしか調べられなかったのもあってできるだけ簡単にしようと思ったのですが, 技量不足で何もできなくて放置になったの申し訳ないです.
該当ファイル (JP-Localize/lua/lang/english.lua) は次のリリース時に消しておきますね.

## その他
実は BLT の原作者のサイト paydaymods.com の ModManager に長い間ログインできず, 問い合わせても返事がないため, アップデートすらもできない状況になっています. なので, おそらくそこらへんのところを削除すると思います.
あと, 自身の環境が大きく変わってデバッグの作業ができなくなったので payday2 に関して MOD を作ることはおそらくしばらくはないと思いますし, 日本語化 MOD に関しても十分な開発ができないと思います.

**Comment by hinataaki** [comment]
対応の検討ありがとうございます
翻訳もやる人がいないのか停滞気味ですから、頻繁な更新は不要かもしれませんね

MOD部分に関しては何も出来ないのでそういった対応をしてくれるだけでも十分有り難い事です。

**Comment by hinataaki** [comment]
更新作業ありがとうございました。

### ファイルの配置不備について ###
確認のため、ファイルを落として解凍したのですが、導入がスムーズにできない状態になっています。
- v1.1では、正しく"JPLocalize\mods\JPLocalize"でlangフォルダやluaフォルダ等の配置に
- v1.2では、"JPLocalize\mods"でlangフォルダやluaフォルダ等の配置に
Readmeに従って導入を試みるとJPLocalizeフォルダが存在せず手間取る方がいる可能性があります。

**Comment by KashEight** [comment]
あ, 完全にそれは私のミスですね, 申し訳ないです.
既に新しいものに差し替えました.

**Comment by hinataaki** [comment]
対応ありがとうございます。
今度はコチラが申し出が原因のミスになるのですが、english.luaを削除するとゲーム自体の翻訳が行われないという致命的な状態になっております。
english.luaという名称だけの内容なしのファイルでも正常に動作したことから、
プログラムの読み込み順でenglish.luaが存在せず、japanese.luaが読み込まれず日本語化されない状態になっていると推測されます。

何度も手間をかけて本当に申し訳ないですが、対応のほどをよろしくお願いします...

**Comment by KashEight** [comment]
おそらく修正できました (テストはできてないのでまたミスがあったら Issue を立ててほしいです).
